<div class="grid gap-5 sm:grid-cols-2">
    <div><label for="from_account_id" class="text-sm font-medium">Dari akun</label><select id="from_account_id" name="from_account_id" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><option value="">Pilih akun asal</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected((string) old('from_account_id', $transfer->from_account_id ?? '') === (string) $account->id)>{{ $account->name }} · {{ $account->currency }} {{ number_format((float) $balances[$account->id], 2, '.', ',') }}</option>@endforeach</select><x-form-error name="from_account_id" /><p class="mt-1 text-xs text-slate-500">Saldo terkini ditampilkan untuk membantu memilih sumber dana.</p></div>
    <div><label for="to_account_id" class="text-sm font-medium">Ke akun</label><select id="to_account_id" name="to_account_id" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><option value="">Pilih akun tujuan</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected((string) old('to_account_id', $transfer->to_account_id ?? '') === (string) $account->id)>{{ $account->name }} · {{ $account->currency }}</option>@endforeach</select><x-form-error name="to_account_id" /></div>
    <div class="sm:col-span-2 flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-500 dark:bg-slate-800/60"><span class="font-medium text-slate-800 dark:text-slate-200">Akun asal</span><span class="h-px flex-1 bg-slate-200 dark:bg-slate-700"></span><x-icon name="transfer"/><span class="h-px flex-1 bg-slate-200 dark:bg-slate-700"></span><span class="font-medium text-slate-800 dark:text-slate-200">Akun tujuan</span></div>
    <div><label for="amount" class="text-sm font-medium">Jumlah</label><input id="amount" name="amount" type="number" inputmode="decimal" min="0.01" step="0.01" value="{{ old('amount', $transfer->amount ?? '') }}" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-xl font-semibold tabular-nums dark:border-slate-700 dark:bg-slate-950"><x-form-error name="amount" /></div>
    <div><label for="fee" class="text-sm font-medium">Biaya transfer</label><input id="fee" name="fee" type="number" inputmode="decimal" min="0" step="0.01" value="{{ old('fee', $transfer->fee ?? '0.00') }}" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 tabular-nums dark:border-slate-700 dark:bg-slate-950"><x-form-error name="fee" /></div>
    <div><label for="transfer_date" class="text-sm font-medium">Tanggal</label><input id="transfer_date" name="transfer_date" type="date" value="{{ old('transfer_date', isset($transfer) ? $transfer->transfer_date->format('Y-m-d') : now()->format('Y-m-d')) }}" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><x-form-error name="transfer_date" /></div>
    <div class="sm:col-span-2"><label for="description" class="text-sm font-medium">Deskripsi <span class="text-slate-400">(opsional)</span></label><textarea id="description" name="description" rows="4" class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950">{{ old('description', $transfer->description ?? '') }}</textarea><x-form-error name="description" /></div>
</div>
