<div x-data="{ type: '{{ old('type', $transaction->type ?? 'expense') }}' }" class="grid gap-5 sm:grid-cols-2">
    <fieldset class="sm:col-span-2"><legend class="text-sm font-medium">Jenis transaksi</legend><input type="hidden" name="type" :value="type"><div class="mt-2 grid grid-cols-3 gap-1 rounded-xl border border-slate-200 bg-slate-100/80 p-1 dark:border-slate-700 dark:bg-slate-950/60">@foreach($types as $value => $label)<button type="button" @click="type = '{{ $value }}'" :class="type === '{{ $value }}' ? ('{{ $value }}' === 'income' ? 'bg-emerald-50 text-emerald-800 shadow-sm ring-1 ring-emerald-200 dark:bg-emerald-950 dark:text-emerald-300 dark:ring-emerald-900' : ('{{ $value }}' === 'expense' ? 'bg-rose-50 text-rose-800 shadow-sm ring-1 ring-rose-200 dark:bg-rose-950 dark:text-rose-300 dark:ring-rose-900' : 'bg-violet-50 text-violet-800 shadow-sm ring-1 ring-violet-200 dark:bg-violet-950 dark:text-violet-300 dark:ring-violet-900')) : 'text-slate-500 hover:bg-white/70 hover:text-slate-800 dark:hover:bg-slate-800 dark:hover:text-slate-200'" class="min-h-11 rounded-lg px-2 text-xs font-semibold sm:text-sm">{{ $label }}</button>@endforeach</div><x-form-error name="type" /></fieldset>
    <div><label for="account_id" class="text-sm font-medium">Akun</label><select id="account_id" name="account_id" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><option value="">Pilih akun</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected((string) old('account_id', $transaction->account_id ?? '') === (string) $account->id)>{{ $account->name }} ({{ $account->currency }})</option>@endforeach</select><x-form-error name="account_id" /></div>
    <div x-show="type !== 'adjustment'"><label for="category_id" class="text-sm font-medium">Kategori</label><select id="category_id" name="category_id" :disabled="type === 'adjustment'" class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $transaction->category_id ?? '') === (string) $category->id)>{{ App\Models\Category::TYPES[$category->type] }} — {{ $category->name }}</option>@endforeach</select><x-form-error name="category_id" /></div>
    <div x-show="type === 'adjustment'"><label for="adjustment_direction" class="text-sm font-medium">Arah penyesuaian</label><select id="adjustment_direction" name="adjustment_direction" :disabled="type !== 'adjustment'" class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950">@foreach($directions as $value => $label)<option value="{{ $value }}" @selected(old('adjustment_direction', $transaction->adjustment_direction ?? 'increase') === $value)>{{ $label }}</option>@endforeach</select><x-form-error name="adjustment_direction" /></div>
    <div class="sm:col-span-2"><label for="amount" class="text-sm font-medium">Nominal</label><div class="relative mt-1"><span class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-4 text-sm font-semibold text-slate-400">{{ $preferences->currency }}</span><input id="amount" name="amount" type="number" inputmode="decimal" min="0.01" step="0.01" value="{{ old('amount', $transaction->amount ?? '') }}" required class="block w-full rounded-xl border border-slate-300 bg-white py-3 pl-14 pr-4 text-2xl font-semibold tabular-nums dark:border-slate-700 dark:bg-slate-950"></div><x-form-error name="amount" /></div>
    <div><label for="transaction_date" class="text-sm font-medium">Tanggal</label><input id="transaction_date" name="transaction_date" type="date" value="{{ old('transaction_date', isset($transaction) ? $transaction->transaction_date->format('Y-m-d') : now()->format('Y-m-d')) }}" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><x-form-error name="transaction_date" /></div>
    <div class="sm:col-span-2"><label for="description" class="text-sm font-medium">Deskripsi <span class="text-slate-400">(opsional)</span></label><textarea id="description" name="description" rows="4" class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950">{{ old('description', $transaction->description ?? '') }}</textarea><x-form-error name="description" /></div>
    <div class="sm:col-span-2"><label for="attachment" class="text-sm font-medium">Lampiran <span class="text-slate-400">(opsional)</span></label><input id="attachment" name="attachment" type="file" accept=".jpg,.jpeg,.png,.pdf" class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950"><x-form-error name="attachment" /><p class="mt-1 text-xs text-slate-500">JPG, PNG, atau PDF; maksimal 5 MB. Berkas disimpan privat dengan nama acak.</p>@if(isset($transaction) && $transaction->attachment)<label class="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" name="remove_attachment" value="1" @checked(old('remove_attachment'))><span>Hapus lampiran saat ini</span></label>@endif</div>
</div>
