<div class="grid gap-5 sm:grid-cols-2">
    <div class="sm:col-span-2"><label for="name" class="text-sm font-medium">Nama tagihan</label><input id="name" name="name" value="{{ old('name', $bill->name ?? '') }}" required maxlength="150" class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><x-form-error name="name" /></div>
    <div><label for="amount" class="text-sm font-medium">Jumlah</label><input id="amount" name="amount" type="number" min="0.01" step="0.01" value="{{ old('amount', $bill->amount ?? '') }}" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 tabular-nums dark:border-slate-700 dark:bg-slate-950"><x-form-error name="amount" /></div>
    <div><label for="due_date" class="text-sm font-medium">Tanggal jatuh tempo</label><input id="due_date" name="due_date" type="date" value="{{ old('due_date', isset($bill) ? $bill->due_date->format('Y-m-d') : '') }}" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><x-form-error name="due_date" /></div>
    <div><label for="category_id" class="text-sm font-medium">Kategori <span class="text-slate-400">(opsional)</span></label><select id="category_id" name="category_id" class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><option value="">Tanpa kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $bill->category_id ?? '') === (string) $category->id)>{{ App\Models\Category::TYPES[$category->type] }} — {{ $category->name }}</option>@endforeach</select><x-form-error name="category_id" /></div>
    <div><label for="recurrence" class="text-sm font-medium">Pengulangan</label><select id="recurrence" name="recurrence" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950">@foreach($recurrences as $value => $label)<option value="{{ $value }}" @selected(old('recurrence', $bill->recurrence ?? 'none') === $value)>{{ $label }}</option>@endforeach</select><x-form-error name="recurrence" /><p class="mt-1 text-xs text-slate-500">Hanya metadata; tagihan berulang tidak dibuat otomatis.</p></div>
    <div><label for="status" class="text-sm font-medium">Status</label><select id="status" name="status" required class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950">@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected(old('status', $bill->status ?? 'unpaid') === $value)>{{ $label }}</option>@endforeach</select><x-form-error name="status" /><p class="mt-1 text-xs text-slate-500">Status lunas tidak membuat transaksi.</p></div>
    <div class="sm:col-span-2"><label for="notes" class="text-sm font-medium">Catatan <span class="text-slate-400">(opsional)</span></label><textarea id="notes" name="notes" rows="4" class="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950">{{ old('notes', $bill->notes ?? '') }}</textarea><x-form-error name="notes" /></div>
</div>
